### ISSUE TITLE
Decimal pointer button supporting all mathematical operations

### ISSUE THREAD

**Issue by mohdsauood** [mohdsauood/js-calculator#10]
#### Add decimal pointer button that performs decimal calculations 
example : 0.2 x 0.2 = 0.4

#### Decimal pointer ui button concept 
![decimal-functionality](https://user-images.githubusercontent.com/35588119/136655598-135b66ea-8b58-4886-b2ab-39fa2663425d.JPG)

**Comment by md-jishan-ansari** [comment]
Assign this issue to me, I can add it

**Comment by NarendraBobbiliJS** [comment]
Please assign this to me.

**Comment by mohdsauood** [comment]
hi @NarendraBobbiliJS ! Please look for other issues . @md-jishan-ansari is handling this one .
