### ISSUE TITLE
Should display "cant divide by 0" instead of "nan" when performing any number divided by 0

### ISSUE THREAD

**Issue by mohdsauood** [mohdsauood/js-calculator#13]
![nan-issue](https://user-images.githubusercontent.com/35588119/136655744-c62c8b7d-a535-4a89-aa71-72b883b840e4.gif)

**Comment by Aryan-kumar-mains** [comment]
We can't divide any number with 0 because it gives infinity, so I think the result of the above operation is right. 
If you want to print 0 instead of NaN then this will be mathematically wrong.

**Comment by omar1024** [comment]
hi, can I work on this ?, if yes pls assign it to me
