### ISSUE TITLE
Buttons rearrange on bigger screens

### ISSUE THREAD

**Issue by sinc0115** [mohdsauood/js-calculator#23]
The calculator looks amazing on smaller screens, but when viewed on larger screens the buttons shift around into more columns, This makes it harder to use because the operators (+ - x etc) are now mixed in with the numbers: 
![Screenshot 2021-10-12 111911](https://user-images.githubusercontent.com/46421126/136985470-cbc9773a-b070-4b7b-991f-65dbd9c6e683.png)

**Comment by mohdsauood** [comment]
hi @sinc0115 ! 

yes the buttons can be improved on larger screen.
