### ISSUE TITLE
Contributions??

### ISSUE THREAD

**Issue by FarbrorGarbo** [mohdsauood/js-calculator#4]
Hi! You have labled this repo with 'hacktoberfest2021'. Anything particular you would like to have help with? Or would you accept any PRs? You should otherwise add some contribution rules so we could suggest what we could focus on.

**Comment by FarbrorGarbo** [comment]
I see you have a CONTRIBUTION.md, however it is quite vague.

**Comment by Shubham56-droid** [comment]
hi @mohdsauood i want to contribute to ur project I will make an awesome UI for ur calculator pls assign the issue to me.

**Comment by mohdsauood** [comment]
hello @FarbrorGarbo ! i agree , i need to add better instructions in the CONTRIBUTION.md . However , i would accept pr's that would optimise the code , add responsiveness to the ui or add any additional feature to the calculator like trigonometric functions .

**Comment by mohdsauood** [comment]
hey @Shubham56-droid i'd appreciate if you could make the ui responsive . Create a pull request directly , no need to raise an issue as of now .

**Comment by Shubham56-droid** [comment]
hi @mohdsauood I have added a pr with all details of what I have changed pls look through it and if u like it pls merge my  full request tell me if u need any further changes the pull request is #5

**Comment by Shubham56-droid** [comment]
Hi bro u have closed the issue I have just added a pull request pls check
it hope u like it I made the web page responsive as u have said pls do
check it
