### ISSUE TITLE
There is no any response on keyboard press

### ISSUE THREAD

**Issue by md-jishan-ansari** [mohdsauood/js-calculator#9]

**Comment by mohdsauood** [comment]
Hi @md-jishan-ansari ! Thanks for raising an issue , sure you can work on the key press events for numbers and mathematical operators . 

#### features
- [ ] typing numbers and mathematical operators through keyboard
- [ ] backspace

**Comment by mohdsauood** [comment]
i have raised new issues @sonalikari , please comment in any of the issues you are interested to work on . Thank you
